# Generated by Django 5.0.2 on 2024-04-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0004_chatgroup_user_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='user_online',
            new_name='users_online',
        ),
    ]
